### ISSUE TITLE
add Imap-Idle-Proxy-ImapServer to ZIMBRA_COMPONET

### ISSUE THREAD

**Issue by yuphing-ong** [nxhack/logstash#1]
My zimbra mailbox.log has some logs like this:
`2016-07-13 16:30:38,695 INFO  [Imap-Idle-Proxy-ImapServer-792] [] imap - dropping connection for user test@email.org (server-initiated)`
To solve this, I just had to modify ZIMBRA_COMPONET and include the alternative:
`ZIMBRA_COMPONET Timer-Zimbra|Junk-NotJunk-Handler|MailboxPurge|btpool|pool|LmtpServer|ImapServer|ImapSSLServer|Imap-Idle-Proxy-ImapServer|Pop3Server|Pop3SSLServer|ScheduledTask|AnonymousIoService|CloudRoutingReaderThread|GC|SocketAcceptor|Thread|Index|FileLogWriter.FsyncThread|IncomingDirectorySweeper|mailboxd.csv|main|SyncGalGroup|%{WORD}`

**Comment by nxhack** [comment]
@yuphing-ong Thank you!
